apiVersion: v1
kind: Service
metadata:
  name: "acme-dns-hetzner"
  labels:
    {{- include "acme-dns-hetzner.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "acme-dns-hetzner.selectorLabels" . | nindent 4 }}
